# Generated by Django 3.0.6 on 2020-06-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgn', models.TextField()),
                ('opening_name', models.CharField(max_length=255)),
                ('eco_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
