# Generated by Django 3.0.6 on 2020-06-05 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChessGame',
            new_name='ChessOpening',
        ),
    ]
