# Generated by Django 3.0.6 on 2020-06-05 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choper', '0002_auto_20200605_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessopening',
            name='eco_code',
            field=models.CharField(default=3, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('pgn', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('side', models.CharField(choices=[('w', 'blanc'), ('b', 'noir')], default='w', max_length=1)),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choper.ChessOpening')),
            ],
        ),
    ]
