# Generated by Django 3.0.6 on 2020-06-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choper', '0003_auto_20200605_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessopening',
            name='eco_code',
            field=models.CharField(default='A00', max_length=10),
        ),
    ]
