# Generated by Django 3.0.6 on 2020-06-20 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choper', '0004_auto_20200605_2101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChessGame',
            new_name='ChessOpeningTest',
        ),
        migrations.RenameModel(
            old_name='ChessOpening',
            new_name='ChessOpeningTree',
        ),
    ]
