# Generated by Django 3.0.6 on 2020-06-22 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choper', '0006_auto_20200621_1709'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChessOpeningTest',
            new_name='ChessOpeningTraining',
        ),
    ]
