# Generated by Django 3.0.6 on 2020-07-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choper', '0008_auto_20200628_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chessopeningtraining',
            name='last_san_move',
        ),
        migrations.RemoveField(
            model_name='chessopeningtraining',
            name='side',
        ),
        migrations.AddField(
            model_name='chessopeningtraining',
            name='date_lastmodified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chessopeningtraining',
            name='is_chess360',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chessopeningtraining',
            name='uci_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chessopeningtraining',
            name='variant',
            field=models.CharField(choices=[('chess', 'Standard'), ('suicide', 'Suicide'), ('giveaway', 'Giveaway'), ('antichess', 'Antichess'), ('atomic', 'Atomic'), ('kingofthehill', 'King of the Hill'), ('racingkings', 'Racing Kings'), ('horde', 'Horde'), ('3check', 'Three-check'), ('crazyhouse', 'Crazyhouse')], default='chess', max_length=50),
        ),
        migrations.AlterField(
            model_name='chessopeningtraining',
            name='fen',
            field=models.TextField(blank=True, default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', null=True),
        ),
    ]
