# Generated by Django 3.0.6 on 2020-07-05 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choper', '0009_auto_20200705_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chessopeningtraining',
            name='fen',
        ),
    ]
