# Generated by Django 3.0.6 on 2020-07-09 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choper', '0011_remove_chessopeningtraining_pgn_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chessopeningtraining',
            name='score',
        ),
    ]
