# Generated by Django 3.0.6 on 2020-07-10 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choper', '0012_remove_chessopeningtraining_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chessopeningtraining',
            options={'ordering': ['date_lastmodified']},
        ),
        migrations.AlterField(
            model_name='chessopeningtraining',
            name='opening_tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening', to='choper.ChessOpeningTree'),
        ),
    ]
